name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:         # Name of inputs
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
